repos:
  # ---------------- commit hooks specific to backend folder only ---------------------------------------------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.14.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        stages: [commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==23.3.12]
        args: ["--config", "backend/.flake8", "--exclude", "*/migrations/*"]
        stages: [commit]
  # ---------------- commit hooks specific to frontend folder only ---------------------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        args:
          [
            "--rule",
            "import/no-unresolved: 0",
            "--rule",
            "import/extensions: 0",
          ]
        additional_dependencies:
          - eslint-plugin-prettier@3.1.4
          - eslint-plugin-vue@9.17.0
          - eslint@8.49.0
          - prettier@3.0.3
        stages: [commit]
        types: [file]
        files: ^frontend/.*\.(js|vue)$
  # ---------------- common commit hooks ---------------------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v1.19.1
    hooks:
      - id: prettier
        stages: [commit]
        types: [file]
        entry: prettier --write --list-different
        files: \.(js|css|scss|sass|vue|yaml|yml|json)$
        exclude: "(.*?)\\.(github)/(\\w+)"
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        stages: [commit]
        args: [-n, "10", "-x", "*/*/*/tests/*"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        stages: [commit]
        exclude: "(.*?)bandwidth-test-image\\.jpeg|(.*?)SumatraPDF\\.exe|(.*?)\\.(github)/(\\w+)"
      - id: check-ast
        stages: [commit]
      - id: fix-byte-order-marker
        stages: [commit]
      - id: check-json
        # VS Code JSON uses comments, so don't validate it
        exclude: "(.*?)\\.(vscode|devcontainer)/(\\w+)\\.json"
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: no-commit-to-branch
        args:
          [
            --branch,
            qa,
            --branch,
            support/qa,
            --branch,
            uat,
            --branch,
            support/uat,
            --branch,
            support/stg,
            --branch,
            prod,
          ]
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
