# Generated by Django 5.1.1 on 2024-09-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"ordering": ("name",), "verbose_name_plural": "facilities"},
        ),
        migrations.AlterModelOptions(
            name="facilitycategory",
            options={
                "ordering": ("name",),
                "verbose_name_plural": "facility categories",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name_plural": "feedback"},
        ),
    ]
