# Generated by Django 5.1.1 on 2024-09-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0002_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_facilitycategory",
                to="park.facilitycategory",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_facility",
                to="park.facility",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="sub_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_subarea",
                to="park.subarea",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_feedback",
                to="park.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subarea_park",
                to="park.park",
            ),
        ),
    ]
