# Generated by Django 5.1.1 on 2024-09-18 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0005_alter_feedback_facility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="facility_category",
        ),
        migrations.RemoveField(
            model_name="subarea",
            name="park",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="sub_area",
        ),
        migrations.AddField(
            model_name="feedback",
            name="park",
            field=models.ForeignKey(
                default=467,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_park",
                to="park.park",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="FacilityCategory",
        ),
        migrations.DeleteModel(
            name="SubArea",
        ),
    ]
