# Generated by Django 5.1.1 on 2024-09-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0006_remove_facility_facility_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="description",
            new_name="comments",
        ),
    ]
