# Generated by Django 5.1.1 on 2024-09-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0007_rename_description_feedback_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="image",
            field=models.TextField(blank=True),
        ),
    ]
