# Generated by Django 5.1.1 on 2024-09-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0009_park_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park",
            name="image",
        ),
        migrations.RemoveField(
            model_name="park",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="park",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="park",
            name="url",
        ),
    ]
