# Generated by Django 5.1.1 on 2024-09-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park", "0011_feature_facility_park_facility_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_facility",
                to="park.facility",
            ),
        ),
    ]
